### PR TITLE
add Rstats package and actions

### PR DESCRIPTION
**Pull request by maxheld83**
this is both an R package that does ghactions, *and* a bunch of R-specific actions, multiple in one repo,

### CODE REVIEW

**Comment by boyney123** [comment]
@maxheld83 for some reason it's blowing up abit in the UI.

You can take a look here: https://deploy-preview-32--github-actions.netlify.com/ghactions

It might be worth just changing the image size before we merge it?

**Comment by maxheld83** [comment]
Great Thanks so much i'll look at it first thing tomorrow!

**Comment by maxheld83** [comment]
Look alright to you now?

**Comment by boyney123** [comment]
Awesome! Looks great! Thanks @maxheld83

**Pull request merged**
